#!/bin/sh

PROG="nginx"
PROG_PATH="/data/app/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

service nginx stop

if [ -d "$PROG_PATH" ] ; then
	rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH
mkdir -p $PROG_PATH/client_body_temp
mkdir -p $PROG_PATH/proxy_temp
mkdir -p $PROG_PATH/logs

cp -v -n -r conf $PROG_PATH/
cp -v -n -r html $PROG_PATH/
cp -v -n -r sbin $PROG_PATH/

cp -v -n nginx  $PROG_PATH/

chmod 666 $PROG_PATH/conf/oauth

ln  -f -s $PROG_PATH/$PROG /etc/init.d/$PROG
update-rc.d  $PROG defaults 30

echo "$MSG_PREFIX install sucess $PROG"

service $PROG start
